# Generated by Django 3.0.8 on 2020-07-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=70)),
                ('py_file', models.FileField(blank=True, upload_to='savedfile')),
            ],
        ),
    ]
